In [5]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

In [7]:
import numpy as np

In [8]:
np.array(my_list)        # single dimensional array or vectors

array([1, 2, 3])

In [9]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_list)          # two dimensional array or matrices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(1,11,2)          # range function using numpy

array([1, 3, 5, 7, 9])

In [16]:
np.zeros(5)               # to get a 1d array of zeros

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((4,12))          # to get a 2d array of zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## IDENTITY MATRIX

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.random.randint(1,100,10)

array([35, 18, 18, 93, 75, 86, 88, 54, 51, 14])

In [32]:
np.random.randint(1,100,(5,10))

array([[ 6, 34, 25, 90, 93, 98, 19, 14, 74, 34],
       [46, 42, 82, 93, 90, 15, 72, 96, 93, 72],
       [19, 46, 12, 22, 12, 43, 73, 68, 30, 59],
       [ 8, 87, 94, 65, 55, 76, 48, 53, 17, 89],
       [11, 69, 97, 18, 89, 56, 20, 36, 14, 46]])

# INDEXING AND SLICING 1D ARRAY

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[:4]

array([1, 2, 3, 4])

In [7]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr[4:]

array([5, 6, 7, 8, 9])

In [10]:
arr[7]

8

# INDEXING AND SLICING 2D ARRAY

In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[1,1]

5

In [15]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [16]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [20]:
arr_2d = np.random.randint(1,100,(5,10))

In [21]:
arr_2d

array([[67, 91,  3, 35, 77, 71, 13, 84, 20, 77],
       [29, 85,  9, 61, 89, 92, 84, 27, 67, 61],
       [83, 87, 99,  1, 22, 58, 96, 68, 53, 92],
       [19, 97, 26, 21, 83,  5, 58, 67, 96, 40],
       [81, 26, 68, 38, 82, 12, 77, 54, 42, 51]])

In [23]:
arr_2d[1:4,3:6]

array([[61, 89, 92],
       [ 1, 22, 58],
       [21, 83,  5]])

In [26]:
arr_2d = np.arange(100).reshape(,10)

In [27]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
arr_2d[-1,3]

93

In [33]:
arr_2d[-2:,-2:]

array([[88, 89],
       [98, 99]])

In [ ]:
arr_2d[]