In [12]:
import numpy as np
import pandas as pd

In [23]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [24]:
labels

['a', 'b', 'c']

In [25]:
my_data

[10, 20, 30]

In [26]:
arr

array([10, 20, 30])

In [27]:
d

{'a': 10, 'b': 20, 'c': 30}

In [28]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [30]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Italy'])

In [31]:
ser2 = pd.Series([2,3,4,5],['USA','Germany','Japan','Italy'])

In [32]:
ser1

USA        1
Germany    2
USSR       3
Italy      4
dtype: int64

In [33]:
ser2

USA        2
Germany    3
Japan      4
Italy      5
dtype: int64

In [34]:
ser1+ser2

Germany    5.0
Italy      9.0
Japan      NaN
USA        3.0
USSR       NaN
dtype: float64

In [35]:
ser4 = pd.Series(data=[sum,max,min],index=[1,2,3])

In [36]:
ser4

1    <built-in function sum>
2    <built-in function max>
3    <built-in function min>
dtype: object

# DATAFRAME

In [57]:
import numpy as np
import pandas as pd
from numpy import random

In [61]:
df = pd.DataFrame(random.randn(5,4),['A','B','C','D','E'],[1,2,3,4])

In [62]:
df

1         2         3         4
A -0.694637 -0.748146  1.378906 -0.906075
B  0.140085  0.573726 -0.321466 -0.206094
C -0.694578 -0.518748  0.627053 -0.100848
D  0.347523  0.811319  1.531207  0.163835
E -0.018306  1.378259 -0.654458 -1.199787

In [71]:
df[[1,2]]

1         2
A -0.694637 -0.748146
B  0.140085  0.573726
C -0.694578 -0.518748
D  0.347523  0.811319
E -0.018306  1.378259

In [73]:
df[3]

A    1.378906
B   -0.321466
C    0.627053
D    1.531207
E   -0.654458
Name: 3, dtype: float64

In [78]:
arr = np.arange(0,20).reshape(5,4)

In [79]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [80]:
df = pd.DataFrame(arr,['a','b','c','d','e'],[1,2,3,4])

In [81]:
df

1   2   3   4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19

In [82]:
df[5] = df[2]**2

In [83]:
df

1   2   3   4    5
a   0   1   2   3    1
b   4   5   6   7   25
c   8   9  10  11   81
d  12  13  14  15  169
e  16  17  18  19  289

In [84]:
df.drop(5,axis=1,inplace=True)

In [85]:
df

1   2   3   4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19

In [92]:
df.iloc[2]

1     8
2     9
3    10
4    11
Name: c, dtype: int32

In [87]:
df

1   2   3   4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15
e  16  17  18  19

In [94]:
df = pd.DataFrame(random.randint(0,100,(5,4)),index=[0,1,2,3,4],columns=['a','b','c','d'])

In [95]:
df

a   b   c   d
0   9  46  85  53
1  14   7   8  24
2  72  40   2  57
3  27  79  40  27
4  77  38  56   1

In [102]:
df.reset_index(inplace=True)

In [103]:
df

index   a   b   c   d
0      0   9  46  85  53
1      1  14   7   8  24
2      2  72  40   2  57
3      3  27  79  40  27
4      4  77  38  56   1

In [112]:
df.drop('index',axis=1,inplace=True)

In [114]:
df

a   b   c   d
0   9  46  85  53
1  14   7   8  24
2  72  40   2  57
3  27  79  40  27
4  77  38  56   1

In [117]:
items = 'CA NY OR WY ND'.split()
df['states'] = items

In [118]:
df

a   b   c   d states
0   9  46  85  53     CA
1  14   7   8  24     NY
2  72  40   2  57     OR
3  27  79  40  27     WY
4  77  38  56   1     ND

In [119]:
df.set_index('states')

a   b   c   d
states                
CA       9  46  85  53
NY      14   7   8  24
OR      72  40   2  57
WY      27  79  40  27
ND      77  38  56   1

In [122]:
df[(df['a']>20) & (df['d']>1)]

a   b   c   d states
2  72  40   2  57     OR
3  27  79  40  27     WY

In [125]:
outer = ['g1','g1','g1','g2','g2','g2','g2']
inner = [1,2,3,1,2,3]
hier_index = list(zip(outer,inner))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [126]:
hier_index

MultiIndex([('g1', 1),
            ('g1', 2),
            ('g1', 3),
            ('g2', 1),
            ('g2', 2),
            ('g2', 3)],
           )

In [129]:
df = pd.DataFrame(random.randn(6,2),index=hier_index,columns=['a','b'],)

In [132]:
df

a         b
g1 1  0.662737 -2.508306
   2  1.441974 -0.607078
   3 -1.837908  1.906108
g2 1  0.321731 -0.131689
   2  0.780624  1.475638
   3  0.163865  0.571803

# HANDLING MISSING DATA

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {'A':[1,2,3],'B':[1,np.nan,np.nan],'C':[np.nan,np.nan,np.nan]}

In [5]:
df = pd.DataFrame(data,index=[10,11,12])

In [6]:
df

A    B   C
10  1  1.0 NaN
11  2  NaN NaN
12  3  NaN NaN

In [12]:
df.dropna(axis=1)

A
10  1
11  2
12  3

In [13]:
df

A    B   C
10  1  1.0 NaN
11  2  NaN NaN
12  3  NaN NaN

In [14]:
df.fillna(value='Fill')

A     B     C
10  1     1  Fill
11  2  Fill  Fill
12  3  Fill  Fill

In [15]:
df

A    B   C
10  1  1.0 NaN
11  2  NaN NaN
12  3  NaN NaN

In [18]:
df.dropna(thresh=1)     # return a dataframe where the row has atleast 1 number value

A    B   C
10  1  1.0 NaN
11  2  NaN NaN
12  3  NaN NaN

In [19]:
data = np.random.randint(0,50,(5,5))

In [20]:
data

array([[45, 18, 32, 15, 13],
       [28, 41, 43, 31, 49],
       [31, 47, 25, 18, 36],
       [22,  2,  8, 18,  9],
       [ 5, 10, 17,  0, 48]])

In [23]:
df = pd.DataFrame(data=data,index=['A','B','C','D','E'],columns=['a','b','c','d','e'])

In [24]:
df

a   b   c   d   e
A  45  18  32  15  13
B  28  41  43  31  49
C  31  47  25  18  36
D  22   2   8  18   9
E   5  10  17   0  48

In [38]:
df**0.5

a         b         c         d         e
A  6.708204  4.242641  5.656854  3.872983  3.605551
B  5.291503  6.403124  6.557439  5.567764  7.000000
C  5.567764  6.855655  5.000000  4.242641  6.000000
D  4.690416  1.414214  2.828427  4.242641  3.000000
E  2.236068  3.162278  4.123106  0.000000  6.928203

In [48]:
np.linspace(0,1,num=10).reshape(5,2)

array([[0.        , 0.11111111],
       [0.22222222, 0.33333333],
       [0.44444444, 0.55555556],
       [0.66666667, 0.77777778],
       [0.88888889, 1.        ]])